# Generated by Django 5.2 on 2025-04-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('inflation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('earnings_quality', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
